-- BG3 GUI Bridge — server-side bootstrap
--
-- What this does:
--   1. On load, writes a small probe file so you can find out exactly where
--      Ext.IO's sandboxed storage lives on disk for your install (see README "Finding BRIDGE_ROOT").
--   2. Every ~500ms, checks for a command.json written by the external desktop GUI.
--   3. Executes the matching command (from Commands.lua, generated from shared/commands.json)
--      or, for the console passthrough, compiles and runs arbitrary pasted Lua.
--   4. Writes the result to status.json so the GUI can show it.
--
-- All file I/O goes through Ext.IO.LoadFile/SaveFile, which BG3SE sandboxes to its own
-- storage root (NOT arbitrary paths) for security. That's fine here: the GUI resolves the
-- same physical folder on disk (see gui/bridge.py) since Proton doesn't virtualize the filesystem.

-- Loads BG3GuiBridge_Commands (generated by shared/sync_commands.py from shared/commands.json).
Ext.Require("Commands.lua")

local BRIDGE_DIR = "BG3GuiBridge"
local PROBE_FILE = BRIDGE_DIR .. "/probe.txt"
local COMMAND_FILE = BRIDGE_DIR .. "/command.json"
local COMMAND_DONE_FILE = BRIDGE_DIR .. "/command.done.json"
local STATUS_FILE = BRIDGE_DIR .. "/status.json"
local LOG_FILE = BRIDGE_DIR .. "/log.txt"

-- BG3SE's sandboxed Lua does not expose the standard `os` library (no os.date/os.time) —
-- use Ext.Timer.MonotonicTime() (milliseconds since some fixed point) instead.
local function nowLabel()
    local ok, ms = pcall(function() return Ext.Timer.MonotonicTime() end)
    if ok and ms then
        return string.format("%.3fs", ms / 1000)
    end
    return "?"
end

local logLines = {}
local function log(msg)
    local line = "[" .. nowLabel() .. "] " .. tostring(msg)
    table.insert(logLines, line)
    if #logLines > 200 then table.remove(logLines, 1) end
    Ext.IO.SaveFile(LOG_FILE, table.concat(logLines, "\n"))
    Ext.Utils.Print("[BG3GuiBridge] " .. tostring(msg))
end

-- ---------------------------------------------------------------------------
-- ctx: helpers exposed to every command body compiled from Commands.lua
-- ---------------------------------------------------------------------------
local ctx = {}

-- Returns the GUIDs of all currently player-controlled party members.
-- Verified against a real, published BG3SE mod (Osi.DB_Players + Osi.IsPartyMember) —
-- NOTE: the calling convention is `Osi.*` (a global table, see BG3Extender/IdeHelpers/
-- ExtIdeHelpers.lua: `Osi = {}`), NOT a bare `Osiris` global — that name doesn't exist.
-- `Ext.Osiris.RegisterListener(...)` is a separate namespace for event listening only.
function ctx.players()
    local guids = {}
    local ok, players = pcall(function() return Osi.DB_Players:Get(nil) end)
    if ok and players then
        for _, playerData in pairs(players) do
            local guid = playerData[1]
            if Osi.IsPartyMember(guid, 1) == 1 then
                table.insert(guids, guid)
            end
        end
    end
    return guids
end

function ctx.log(msg)
    log(msg)
end

-- ---------------------------------------------------------------------------
-- Build dispatch table from the generated Commands.lua manifest mirror
-- ---------------------------------------------------------------------------
local dispatch = {}

local function buildDispatch()
    dispatch = {}
    if not BG3GuiBridge_Commands then
        log("Commands.lua not loaded / BG3GuiBridge_Commands missing")
        return
    end
    for _, cmd in ipairs(BG3GuiBridge_Commands) do
        -- Explicit _ENV so this dynamically-compiled chunk sees BG3SE's injected
        -- globals (Osiris, Ext, ...) the same way this file's own top-level code does —
        -- load() does NOT inherit them automatically without this.
        local chunk, err = load("return function(params, ctx) " .. cmd.lua .. " end", cmd.id, "t", _ENV)
        if chunk then
            dispatch[cmd.id] = chunk()
        else
            log("Failed to compile command '" .. cmd.id .. "': " .. tostring(err))
        end
    end
    log("Loaded " .. #BG3GuiBridge_Commands .. " command(s)")
end

-- ---------------------------------------------------------------------------
-- Command execution
-- ---------------------------------------------------------------------------
local function runAction(action, params)
    local fn = dispatch[action]
    if not fn then
        return false, "unknown action: " .. tostring(action)
    end
    local ok, resultOrErr = pcall(fn, params or {}, ctx)
    if ok then
        return true, tostring(resultOrErr)
    else
        return false, "error: " .. tostring(resultOrErr)
    end
end

local function runRawLua(code)
    local chunk, err = load(code, "console", "t", _ENV)
    if not chunk then
        return false, "compile error: " .. tostring(err)
    end
    local ok, resultOrErr = pcall(chunk)
    if ok then
        return true, "ok" .. (resultOrErr ~= nil and (" -> " .. tostring(resultOrErr)) or "")
    else
        return false, "runtime error: " .. tostring(resultOrErr)
    end
end

local function writeStatus(fields)
    local ok, ms = pcall(function() return Ext.Timer.MonotonicTime() end)
    fields.updatedAt = ok and ms or 0
    Ext.IO.SaveFile(STATUS_FILE, Ext.Json.Stringify(fields))
end

-- ---------------------------------------------------------------------------
-- Poll loop
-- ---------------------------------------------------------------------------
local tickCounter = 0
local POLL_EVERY_TICKS = 30 -- roughly ~0.5s at 60fps; adjust if it feels laggy/spammy

local function onTick()
    tickCounter = tickCounter + 1
    if tickCounter < POLL_EVERY_TICKS then return end
    tickCounter = 0

    local raw = Ext.IO.LoadFile(COMMAND_FILE)
    if not raw or raw == "" then return end

    local okParse, cmd = pcall(function() return Ext.Json.Parse(raw) end)
    if not okParse or not cmd then
        log("Failed to parse command.json")
        Ext.IO.SaveFile(COMMAND_FILE, "")
        return
    end

    -- Consume immediately so we don't re-run the same command every poll.
    Ext.IO.SaveFile(COMMAND_FILE, "")

    local ok, message
    if cmd.action == "__raw__" then
        ok, message = runRawLua(cmd.raw_lua or "")
    else
        ok, message = runAction(cmd.action, cmd.params)
    end

    log((ok and "OK " or "FAIL ") .. tostring(cmd.action) .. ": " .. tostring(message))
    writeStatus({
        lastCommandId = cmd.id,
        lastAction = cmd.action,
        ok = ok,
        message = message,
    })
end

Ext.Events.Tick:Subscribe(onTick)

-- ---------------------------------------------------------------------------
-- Init
-- ---------------------------------------------------------------------------
local function init()
    Ext.IO.SaveFile(PROBE_FILE, "BG3GuiBridge probe file. If you can see this via a Linux path, that path (minus this filename) is your BRIDGE_ROOT.\nWritten at (monotonic): " .. nowLabel())
    Ext.IO.SaveFile(COMMAND_FILE, "")
    buildDispatch()
    writeStatus({ lastCommandId = nil, lastAction = nil, ok = true, message = "bridge mod loaded" })
    log("BG3 GUI Bridge ready")
end

Ext.Events.SessionLoaded:Subscribe(init)
