-- AUTO-GENERATED by shared/sync_commands.py from shared/commands.json
-- Do not edit by hand; edit commands.json and re-run the sync script instead.
BG3GuiBridge_Commands = {
  {
    id = "god_mode_on",
    label = "God Mode: ON",
    category = "Health",
    confidence = "verified-pattern",
    lua = [[local n = 0
for _, guid in ipairs(ctx.players()) do
  Osiris.ApplyStatus(guid, 'SG_Immortal', -1, 0)
  n = n + 1
end
return 'god mode ON for ' .. n .. ' character(s)']],
  },
  {
    id = "god_mode_off",
    label = "God Mode: OFF",
    category = "Health",
    confidence = "verified-pattern",
    lua = [[local n = 0
for _, guid in ipairs(ctx.players()) do
  Osiris.RemoveStatus(guid, 'SG_Immortal')
  n = n + 1
end
return 'god mode OFF for ' .. n .. ' character(s)']],
  },
  {
    id = "heal_full",
    label = "Full Heal Party",
    category = "Health",
    confidence = "verified-pattern",
    lua = [[local n = 0
for _, guid in ipairs(ctx.players()) do
  local e = Ext.Entity.Get(guid)
  if e and e.Health then
    e.Health.Hp = e.Health.MaxHp
    e:Replicate('Health')
    n = n + 1
  end
end
return 'healed ' .. n .. ' character(s)']],
  },
  {
    id = "revive_downed",
    label = "Revive Downed Companions",
    category = "Health",
    confidence = "needs-testing",
    lua = [[local n = 0
for _, guid in ipairs(ctx.players()) do
  Osiris.RemoveStatus(guid, 'KNOCKED_DOWN')
  local e = Ext.Entity.Get(guid)
  if e and e.Health then
    e.Health.Hp = math.max(1, math.floor(e.Health.MaxHp * 0.5))
    e:Replicate('Health')
  end
  n = n + 1
end
return 'attempted revive on ' .. n .. ' character(s)']],
  },
  {
    id = "add_gold",
    label = "Add Gold",
    category = "Resources",
    confidence = "needs-testing",
    lua = [[local target = ctx.players()[1]
if not target then return 'no player character found' end
local amount = params.amount or 500
local ok = Osiris.TemplateAddTo('GOLD_TEMPLATE_REPLACE_ME', target, amount, 1)
return 'add gold -> ' .. tostring(ok) .. ' (verify GOLD_TEMPLATE_REPLACE_ME first)']],
  },
  {
    id = "add_xp",
    label = "Add XP",
    category = "Resources",
    confidence = "needs-testing",
    lua = [[local target = ctx.players()[1]
if not target then return 'no player character found' end
local amount = params.amount or 1000
local ok = pcall(function() Osiris.AddXP(target, amount) end)
return 'add xp -> ' .. tostring(ok) .. ' (verify Osiris.AddXP exists in your version)']],
  },
  {
    id = "add_camp_supplies",
    label = "Add Camp Supplies",
    category = "Resources",
    confidence = "needs-testing",
    lua = [[local amount = params.amount or 100
local ok = pcall(function() Osiris.CampAddSupplies(amount) end)
return 'add camp supplies -> ' .. tostring(ok) .. ' (verify Osiris.CampAddSupplies exists)']],
  },
  {
    id = "long_rest",
    label = "Long Rest Anywhere",
    category = "Utility",
    confidence = "needs-testing",
    lua = [[local ok = pcall(function() Osiris.ForceLongRest() end)
return 'long rest -> ' .. tostring(ok) .. ' (verify Osiris.ForceLongRest exists)']],
  },
  {
    id = "unlock_all_recipes",
    label = "Unlock All Recipes",
    category = "Utility",
    confidence = "needs-testing",
    lua = [[return 'not implemented yet - fill in the correct Osiris/Ext call and re-sync']],
  },
  {
    id = "spawn_item",
    label = "Spawn Item by Template ID",
    category = "Utility",
    confidence = "verified-pattern",
    lua = [[local target = ctx.players()[1]
if not target then return 'no player character found' end
if not params.template or params.template == '' then return 'set a template id first' end
local ok = Osiris.TemplateAddTo(params.template, target, params.amount or 1, 1)
return 'spawn item -> ' .. tostring(ok)]],
  },
  {
    id = "free_respec",
    label = "Trigger Free Respec",
    category = "Abilities",
    confidence = "needs-testing",
    lua = [[return 'not implemented yet - fill in the correct Osiris/Ext call and re-sync']],
  },
  {
    id = "unlock_all_spells",
    label = "Unlock All Known Spells",
    category = "Abilities",
    confidence = "needs-testing",
    lua = [[return 'not implemented yet - fill in the correct Osiris/Ext call and re-sync']],
  },
}
