#!/usr/bin/env python3
"""
Regenerates the mod's Commands.lua from the canonical shared/commands.json manifest.

Run this after editing commands.json:

    python3 shared/sync_commands.py

Then repack/reinstall the mod (see README.md) for the change to take effect in-game.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "shared" / "commands.json"
OUT = ROOT / "mod" / "Mods" / "BG3GuiBridge" / "ScriptExtender" / "Lua" / "Commands.lua"


def lua_string_literal(s: str) -> str:
    # Use a long-bracket string so multi-line Lua bodies don't need escaping.
    # Guard against the body itself containing "]]" by picking a longer bracket level.
    level = 0
    marker = "]" + ("=" * level) + "]"
    while marker in s:
        level += 1
        marker = "]" + ("=" * level) + "]"
    eq = "=" * level
    return f"[{eq}[{s}]{eq}]"


def main():
    data = json.loads(MANIFEST.read_text())
    commands = data["commands"]

    lines = []
    lines.append("-- AUTO-GENERATED by shared/sync_commands.py from shared/commands.json")
    lines.append("-- Do not edit by hand; edit commands.json and re-run the sync script instead.")
    lines.append("BG3GuiBridge_Commands = {")
    for cmd in commands:
        lines.append("  {")
        lines.append(f"    id = {json.dumps(cmd['id'])},")
        lines.append(f"    label = {json.dumps(cmd.get('label', cmd['id']))},")
        lines.append(f"    category = {json.dumps(cmd.get('category', 'Misc'))},")
        lines.append(f"    confidence = {json.dumps(cmd.get('confidence', 'needs-testing'))},")
        lines.append(f"    lua = {lua_string_literal(cmd['lua'])},")
        lines.append("  },")
    lines.append("}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({len(commands)} commands)")


if __name__ == "__main__":
    main()
